---
php_repo: "ppa:ondrej/php"
php_packages:
  - php7.0-common
  - php7.0-cli
  - php7.0-intl
  - php7.0-curl
  - php7.0-cgi
  - php7.0-fpm
  - php7.0-mysql
  - php7.0-gd
  - php7.0-mbstring
  - php7.0-mcrypt
  - php7.0-memcached
  - php7.0-apcu
  - php7.0-xml
